if: tag IS present
language: go
os:
  - linux
  - osx
  - windows
go:
  - 1.13.3
addons:
  apt:
    packages:
      - libx11-dev
      - mesa-common-dev
      - libglfw3-dev
      - libgles2-mesa-dev
      - libasound2-dev
script:
  - mkdir -p ./build_artifacts/opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - mkdir -p ./build_artifacts/out
  - go get
  - go build .
  - if [ "$TRAVIS_OS_NAME" = "win" ]; then cp ./OpenDiablo2.exe ./build_artifacts/opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME ; else cp ./OpenDiablo2 ./build_artifacts/opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME; fi
  - cp ./config.json ./build_artifacts/opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME
  - tar -cvzf opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz ./build_artifacts/$TRAIVS_OS_NAME
git:
  depth: 1
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: "$GithubApi"
  file: opendiablo2-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz
  skip_cleanup: true
  name: "OpenDiablo Unstable"
  prerelease: true
  on:
    tags: true
