language: go
os:
  - linux
  - osx
  - windows
go:
  - 1.13.3
addons:
  apt:
    packages:
      - libx11-dev
      - mesa-common-dev
      - libglfw3-dev
      - libgles2-mesa-dev
      - libasound2-dev
script:
  - git config --local user.name "$GitUser"
  - git config --local user.email "$GitEmail"
  - git tag Build-Master-$TRAVIS_OS_NAME -m "Update build version file with $TRAVIS_BUILD_NUMBER"
  - mkdir -p ./build_artifacts
  - go get
  - go build .
  - if [ "$TRAVIS_OS_NAME" = "win" ]; then cp ./OpenDiablo2.exe ./build_artifacts ; else cp ./OpenDiablo2 ./build_artifacts; fi
  - cp ./config.json ./build_artifacts
git:
  depth: 1
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: "$GithubApi"
  file_glob: true
  file: build_artifacts/*
  skip_cleanup: true
  name: "OpenDiablo Git Latest ($TRAVIS_OS_NAME)"
  on:
    tags: true
